name: "Podcast Generator"
author: "Saimon Islam."
description: "Generatesa feed for podcast from YAML file"
runs:
    usign: "docker"
    image: "Dockerfile"
branding: 
    icon: "git-branch"
    color: "red"
    
inputs: 
    email:
        description: The commites email address
        required: true
        default: ${{ github.actor}}@localhost
    name:
        description: The committers name 
        required: true 
        default: ${{ github.actor }}
